config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end

  resources :emails, only: %i(index new create show) do
    get :sent, on: :collection
  end
  devise_for :users
  root to: 'pages#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
# frozen_string_literal: true

class Email < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_and_belongs_to_many :recipients, class_name: 'User'

  validates :subject, :body, :recipients, :sender, presence: true

  after_save :send_mail
  scope :latest, ->(page) { order(created_at: :desc).page(page || 1) }

  def send_mail
    UserMailer.custom_mail(self).deliver_now
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  enum role: %i(user admin)
  has_and_belongs_to_many :recived_emails, class_name: 'Email'
  has_many :sent_emails, class_name: 'Email', foreign_key: :sender_id
  validates :name, :email, presence: true
  validates :password, :password_confirmation, presence: true, on: :create

  def info
    "#{name} <#{email}>"
  end
end

app/controllers/admin/admin_controller.rb
# frozen_string_literal: true

module Admin
  class AdminController < ApplicationController
    before_action :authenticate_user!
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < AdminController
    before_action :set_user, only: %i(edit update destroy show)

    def index
      authorize :user
      @users = User.all.page(params[:page] || 0)
    end

    def new
      @user = User.new
      authorize @user
    end

    def create
      @user = User.new(user_params)
      authorize @user

      return redirect_to(admin_users_url, notice: 'User was successfully created.') if @user.save
      render :new
    end

    def show; end

    def edit; end

    def update
      return redirect_to(admin_user_url(@user), notice: 'User was successfully updated.') if @user.update(user_params)
      render :edit
    end

    def destroy
      @user.destroy
      redirect_to admin_users_url, notice: 'User was successfully destroyed.'
    end

    private

    # get user params from request params and ignore password and password_confirmation if blank
    def user_params
      params
        .require(:user)
        .permit(:name, :email, :password, :password_confirmation, :role)
        .delete_if { |k, v| %w(password password_confirmation).include?(k) && v.blank? }
    end

    def set_user
      @user = User.find(params[:id])
      authorize @user
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referer || root_path)
  end
end

app/controllers/emails_controller.rb
# frozen_string_literal: true

class EmailsController < ApplicationController
  before_action :authenticate_user!

  def index
    authorize :email
    @emails = current_user.recived_emails.preload(:sender).latest(params[:page])
  end

  def sent
    authorize :email
    @emails = current_user.sent_emails.preload(:recipients).latest(params[:page])
  end

  def new
    @email = Email.new
    authorize @email
  end

  def show
    @email = Email.preload(:sender, :recipients).find(params[:id])
    authorize @email
  end

  def create
    @email = Email.new(email_params)
    authorize @email
    @email.recipients = User.where(id: params[:email][:recipients])
    return redirect_to(emails_url, notice: 'Email sent successfully.') if @email.save
    render :new
  end

  private

  def email_params
    params.require(:email).permit(:subject, :body).merge(sender: current_user)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin
  module UsersHelper
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/emails_helper.rb
# frozen_string_literal: true

module EmailsHelper
  def system_users
    User.all.map { |u| [u.info, u.id] }
  end

  def recipients(email, info = false)
    content_tag :div, class: 'recipients-list' do
      email.recipients.collect do |recipient|
        if info
          concat content_tag(:span, recipient.info)
        else
          concat content_tag(:span, recipient.name, title: recipient.email, class: 'label label-default')
        end
      end
    end
  end
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/admin/users/_form.html.haml
= simple_form_for(@user, url: url, validate: true) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, placeholder: 'Jhon'
    = f.input :email, placeholder: 'user@example.com'
    = f.input :role, collection: User.roles.keys, as: :radio_buttons
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit
    = link_to 'Cancel', admin_users_url, class: 'btn btn-danger'

app/views/admin/users/edit.html.haml
%h2.page-title Edit User

= render 'form', url: admin_user_path(@user)

app/views/admin/users/index.html.haml
= link_to 'New User', new_admin_user_path

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th Name
      %th Email
      %th Role
      %th Last sign in at
      %th Actions
  %tbody
    - if @users.any?
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= user.role
          %td= user.last_sign_in_at
          %td
            = link_to 'Show', admin_user_path(user)
            = link_to 'Edit', edit_admin_user_path(user)
            = link_to 'Destroy', admin_user_path(user), :method => :delete, :data => { :confirm => 'Are you sure?' }
    - else
      %tr
        %td.text-center{'colspan' => 5} No users found
%br
= paginate @users

app/views/admin/users/new.html.haml
%h2.page-title New User

= render 'form', url: admin_users_path

app/views/admin/users/show.html.haml
%h2.page-title Show User

%p
  %b Name:
  = @user.name || 'N/A'
%p
  %b Email:
  = @user.email
%p
  %b Role:
  = @user.role
%p
  %b Last sign in at:
  = @user.last_sign_in_at
%p
  %b Last sign in IP:
  = @user.last_sign_in_ip
%p
  %b Last sign in count:
  = @user.sign_in_count

= link_to 'Back', admin_users_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MailingClient
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/header'
    .container
      = render 'shared/messages'
      = yield
    = render 'shared/footer'

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MailingClient
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/header'
    .container
      .col-md-offset-2.col-md-8
        = render 'shared/messages'
        = yield
    = render 'shared/footer'

app/views/pages/index.html.haml
.container
  .row
    .text-center
      - if user_signed_in?
        = link_to 'Emails', emails_url, class: 'btn btn-info btn-lg'
      - else
        = link_to 'Sign in', new_user_session_url, class: 'btn btn-success btn-lg'

app/views/shared/_footer.html.haml
%footer.footer
  .container
    %p.text-muted.text-center Copyright @copy 2017

app/views/shared/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_url} Mailing Client
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          - if policy(:user).index?
            %li= link_to 'Users', admin_users_url
          - if policy(:email).index?
            %li= link_to 'Inbox', emails_url
          - if policy(:email).sent?
            %li= link_to 'Sent', sent_emails_url
          %li= link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Login', new_user_session_path

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value